package namesgenerator // import "github.com/docker/docker/pkg/namesgenerator"

import (
	"fmt"
	"math/rand"
)

var (
	left = [...]string{
		"admiring",
		"adoring",
		"affectionate",
		"agitated",
		"amazing",
		"awesome",
		"beautiful",
		"blissful",
		"bold",
		"brave",
		"busy",
		"charming",
		"clever",
		"cool",
		"compassionate",
		"competent",
		"condescending",
		"confident",
		"cranky",
		"crazy",
		"dazzling",
		"determined",
		"dreamy",
		"eager",
		"ecstatic",
		"elastic",
		"elated",
		"elegant",
		"eloquent",
		"epic",
		"exciting",
		"fervent",
		"festive",
		"flamboyant",
		"focused",
		"friendly",
		"frosty",
		"funny",
		"gallant",
		"gifted",
		"goofy",
		"gracious",
		"great",
		"happy",
		"hardcore",
		"heuristic",
		"hopeful",
		"hungry",
		"infallible",
		"inspiring",
		"interesting",
		"intelligent",
		"jolly",
		"jovial",
		"keen",
		"kind",
		"laughing",
		"loving",
		"lucid",
		"magical",
		"mystifying",
		"modest",
		"musing",
		"naughty",
		"nice",
		"nifty",
		"nostalgic",
		"objective",
		"optimistic",
		"peaceful",
		"pedantic",
		"pensive",
		"practical",
		"priceless",
		"quirky",
		"quizzical",
		"recursing",
		"relaxed",
		"reverent",
		"romantic",
		"serene",
		"sharp",
		"silly",
		"stoic",
		"stupefied",
		"sweet",
		"tender",
		"trusting",
		"unruffled",
		"upbeat",
		"vibrant",
		"vigilant",
		"vigorous",
		"wizardly",
		"wonderful",
		"xenodochial",
		"youthful",
		"zealous",
		"zen",
	}

	// Docker, starting from 0.7.x, generates names from notable scientists and hackers.
	// Please, for any amazing man that you add to the list, consider adding an equally amazing woman to it, and vice versa.
	right = [...]string{
		 "eleanor_williams",
                 "martin_luther",
                 "rosa_park",
                 "michael_jackson",
                 "george_weah",
                 "usaim_bolt",
                 "barack_obama",
                 "gladys_west",
                 "kobe_bryant",
                 "michael_jordan",
                 "miles_davis",
                 "stevie_wonder",
                 "nelson_mandela",
                 "aliko_dangote",
                 "kesley_hightower",
                 "oprah_winfrey",
                 "denzel_washington",
                 "whitney_houston",
                 "francois_locoh-donou",
                 "2PAC",
                 "mark_dean",
                 "koffi_djondo",
		 "kwame_nkrumah",
		 "patrice_lumumba",
		 "behanzin",
		 "wole_soyinka",
		 "tony_elumelu",
		 "myriam_makeba",
		 "sedar_senghor",
		 "thomas_sankara",
		 "muhamad_ali",
		 "bob_marley",
		 "marcus_garvey",
		 "lucky_dube",
		 "mansa_musa",
		 "pele",
		 "frantz_fanon",
		 "desmund_tutu",
		 "soundjata_keita",
		 "toussaint_louverture",
		 "george_washington",
		 "howard_latimer",
		 "ayanna_howard",
		 "chimamanda_ngozi",
		 "modibo_diarra",
		 "trevor_noah",
		 "tidjane_thiam",
		 "strive_masiyiwa",
		 "denis_mukwege",
		 "mitchell_elegbe",
		 "david_adjaye",
		 "lupita_nyongo",
		 "sim_tsabalala",
		 "achille_mbembe",

	}
)

// GetRandomName generates a random name from the list of adjectives and surnames in this package
// formatted as "adjective_surname". For example 'focused_turing'. If retry is non-zero, a random
// integer between 0 and 10 will be added to the end of the name, e.g `focused_turing3`
func GetRandomName(retry int) string {
begin:
	name := fmt.Sprintf("%s_%s", left[rand.Intn(len(left))], right[rand.Intn(len(right))])
	if name == "boring_wozniak" /* Steve Wozniak is not boring */ {
		goto begin
	}

	if retry > 0 {
		name = fmt.Sprintf("%s%d", name, rand.Intn(10))
	}
	return name
}
